### ISSUE TITLE
clickstream session classification

### ISSUE THREAD

**Issue by polya20** [hidasib/GRU4Rec#13]
So I have the data in the following form,  I use char-rnn/word-rnn to predict the next click and classify if the user will convert or not. The question is what changes need to be made to incorporate to classify if a user given the user cicks is going to buy or defer. A quick rough brain dump is sufficient.
<unique session><web page clicks where Pi denotes the exact webpage><final classfication>
Session1,P19,P69,P71,P72,P24,Buy
Session2,P0,P6,P14,P10,P18,P32,P50,Defer
Session3,P7,P0,P26,P6,P33,Defer
Session4,P10,P6,P11,P12,Defer
Session5,P2,P10,P18,P32,Defer
Session6,P0,P10,P18,P32,P50,P37,P7,Buy
Session7,P10,P18,P32,P50,P37,Buy
Session8,P0,P33,P40,P7,P10,P18,Defer
Session9,P10,P18,P7,P0,P6,P33,P14,P5,P68,P32,P50,P37,Buy
Session10,P10,P7,P0,P18,P32,Defer
Session11,P10,P18,P32,P50,P37,Buy
Session12,P11,P7,P0,P10,P18,Defer
Session13,P0,P3,P39,P30,P26,P7,P36,P20,Defer
Session14,P0,P10,P18,P32,P50,P37,Buy
Session15,P6,P28,P26,P7,P8,Defer
Session16,P10,P7,P26,P5,P68,P82,P84,P37,Buy
Session17,P10,P18,P32,P50,P37,Buy
Session18,P7,P23,P34,P35,P37,Buy

**Comment by hidasib** [comment]
This question is not related to this repo. But if you want to do classification, you can use the session representation (e.g. last value of the hidden state, combined value of hidden states with attention, etc) as an input of the classifier.
