### ISSUE TITLE
Is the problem a sequence predict a value? 

### ISSUE THREAD

**Issue by siyuan126** [hidasib/GRU4Rec#14]
I am a little confused about what the problem here is. Are we trying to use all the previous clicks in a sequence to predict last click in that sequence? If so, how is it possible to calculate recall @ 20? If it is a classification problem, how so?

**Comment by DaveGeneral** [comment]
through the implementation, the truth is see whether the ground true(the real click) is in the predict top20 or not, and it's not predict the 'last' click, it's the next click, and add the loss and recall every step together @siyuan126
