### ISSUE TITLE
In traing data the items are indexed, but in test data are not, is there anything wrong?

### ISSUE THREAD

**Issue by xuerenlv** [hidasib/GRU4Rec#15]
in traing data:
`self.predict = None
  self.error_during_train = False
  itemids = data[self.item_key].unique()
  if not retrain:
            self.n_items = len(itemids)
            self.itemidmap = pd.Series(data=np.arange(self.n_items), index=itemids)
            data = pd.merge(data, pd.DataFrame({self.item_key: itemids, 'ItemIdx': self.itemidmap[itemids].values}), on=self.item_key, how='inner')
            offset_sessions = self.init(data)`

and use "ItemIdx":
`out_idx = data.ItemIdx.values[start]`

but in test data(use "item_key"):
`in_idx[valid_mask] = test_data[item_key].values[start_valid]`

Is there anything wrong?

**Comment by xuerenlv** [comment]
I missed something.

**Comment by LouHerGetUp** [comment]
> I missed something.

Hi, can you tell me how you solved this problem? I'm having the same problem.
