### ISSUE TITLE
Please add a license 

### ISSUE THREAD

**Issue by FlorianWilhelm** [hidasib/GRU4Rec#19]
It seems that there is right now no statement about any kind of license which is problematic when using the code. Could you please state a license, for instance the MIT license?

**Comment by hidasib** [comment]
I'll put up a license, but it is a work in progress. I hope we can get to it in the next few weeks. (I'll also publish a considerable speed-up update along with the license.)

The basic idea for the license is that the code is free to use for research (publications should cite the two papers describing this algorithm), but the derivative code can't be sold or used in commercial systems. For use in commercial systems you'll need to ask for a separate license.

**Comment by FlorianWilhelm** [comment]
@hidasib, thanks for the fast response. I understand your hesitance of putting your code under MIT which would also allow commercial use of your work. There are already reimplementations of your code like [here](https://github.com/yhs-968/pyGRU4REC) which also lack a proper license statement.  

I wonder if you are already earning money by selling commercial licenses since a clean-room implementation, only based on your paper, would also be a legal way to commercially use the GRU4Rec method without such a commercial license. So my actual point is, wouldn't it be easier for everyone involved to distribute under MIT/BSD/Apache2 as many great open source projects like Scikit-Learn, LightFM, Pandas etc. do in the spirit of sharing?

**Comment by hidasib** [comment]
License was added earlier this year, closing issue.
