### ISSUE TITLE
Strange CPU usage

### ISSUE THREAD

**Issue by ghost** [hidasib/GRU4Rec#2]
Hi, I'm training the neural network using Recsys2015 dataset and I'm facing with an unexpected CPU utilization (see screenshot below):

![schermata del 2016-05-06 12-35-01](https://cloud.githubusercontent.com/assets/12090833/15070875/af7dfc80-1387-11e6-8a22-94970a528f04.png)

It seems that CPU cores aren't properly used (only 1 core out of 16 is fully used, the others are mostly spending their time in kernel-related cycles -- red bars). Can you help me with that? I tested my Theano installation and everything works fine, Theano's test script uses all cores at almost 100%.

Thanks!

**Comment by arccos2002** [comment]
where's the dataset's url?

**Comment by hidasib** [comment]
The processor usage issue is probably due Theano calling lots of short BLAS operations.

**Comment by hidasib** [comment]
@arccos2002: Although I have no idea, why the question about the URL of the dataset is in this thread, since you asked so nicely: http://bit.ly/2hv5UGQ
