### ISSUE TITLE
Initial Click data

### ISSUE THREAD

**Issue by prakhar987** [hidasib/GRU4Rec#21]
The model proposed works once a person has sufficient click data. For training and evaluation, Recsys data was used.

Lets say one wants to deploy this method. Then how do we get the initial click data ?
The customers will need "some level of similar products" recommended before they start clicking and generate the data right?
How do we handle this cold-start of the entire model?

**Comment by hidasib** [comment]
One of the nice things about session-based recommenders - such as GRU4Rec - is that they automatically handle the user cold-start problem. The model is trained on sessions from the past and it learns how to continue a sequence of events (i.e sessions). So as soon as the user has a single vent on the site (e.g. views one item), the model can recommend items that are suitable for continuing the session. And as the session of the user evolves, the model adapts its recommendations.
