### ISSUE TITLE
NOT RNN MODEL

### ISSUE THREAD

**Issue by yufengwhy** [hidasib/GRU4Rec#30]
[The code](https://github.com/hidasib/GRU4Rec/blob/master/gru4rec.py#L414) only define a timestep of rnn, so gradient of timestep >=(t+2) cannot be propogated to timestep t ? which is more like a Markov Assumption (only timestep t and timestep t+1 have relations) rather than a rnn Assumption?

**Comment by yufengwhy** [comment]
In other words, the forward is like rnn, while the backward is like Markov  model.

**Comment by hidasib** [comment]
If you are referring the lack of BPTT, check out issue #22 and the updated readme. The tl;dr version is that it doesn't improve performance on real life session data in experiments so was not included in the public version. Might be added later for folks working with longer sequences.
