### ISSUE TITLE
Additional Negative Sampling: Conditional Statement Logic Error

### ISSUE THREAD

**Issue by yhshu** [hidasib/GRU4Rec#31]
https://github.com/hidasib/GRU4Rec/blob/0438f25ce667aa907d3e3b0b159ecda56991a4cb/gru4rec.py#L554

https://github.com/hidasib/GRU4Rec/blob/0438f25ce667aa907d3e3b0b159ecda56991a4cb/gru4rec.py#L564

https://github.com/hidasib/GRU4Rec/blob/0438f25ce667aa907d3e3b0b159ecda56991a4cb/gru4rec.py#L566

The conditional logic of these three lines seems to be unreasonable. Is the branch starting at line 566 redundant?
```
if self.n_sample:
                            if sample_pointer == generate_length:
                                generate_samples()
                                sample_pointer = 0
                            sample_pointer += 1
```

Also, I did not see the definition of the function `generate_samples`.
Thanks.

**Comment by hidasib** [comment]
Same as #32 . That function was not supposed to get into the public version that time, but has been included in the recent update along with other speedups.
