### ISSUE TITLE
Fit function in gru4rec.py missing data sort

### ISSUE THREAD

**Issue by dawn-farsi** [hidasib/GRU4Rec#35]
Thank you for sharing your great job. In gru4rec.py file, I think data should be sorted by session_key and item_key after line 508 to be aligned to offset_sessions.

**Comment by TauraiUCB** [comment]
Hi @sfarsinezhad I have encountered the same problem during testing. 

```
 start = offset_sessions[iters]
IndexError: index 2 is out of bounds for axis 0 with size 2
```
How precisely were you able to fix it?
