### ISSUE TITLE
Saving a model

### ISSUE THREAD

**Issue by pabloloyola** [hidasib/GRU4Rec#4]
Hi, if I want save a model, should I  care about the following objects ?
 self.Wx, self.Wh, self.Wrz, self.Bh, self.H 

thank you!

**Comment by hidasib** [comment]
Use pickle to save the whole GRU object.

**Comment by loretoparisi** [comment]
@pabloloyola  @hidasib is it possibile to save using the dump like `theano.misc.pkl_utils.dump(gru,...`), supposed that the whole `gru` object is serializable?
