### ISSUE TITLE
Can you make a brief explaination on how you calculate recall ?

### ISSUE THREAD

**Issue by H13U1999** [hidasib/GRU4Rec#41]
The way to calculate recall is Recall = TP/(TP + FN), but in the evaluation, I do not completely understand the way you calculate it, can you make a brief explanation on this? Thank you.

**Comment by giaabaoo** [comment]
Can you show me how to calculate the Precision too? Did you count the number of true positives then divide it by the number of all relevant items like the normal way? I tried to output your ranks tensor but I don't think I understand what it is. I would be very grateful. Thanks guys.

**Comment by giaabaoo** [comment]
> 
> 
> Can you show me how to calculate the Precision too? Did you count the number of true positives then divide it by the number of all relevant items like the normal way? I tried to output your ranks tensor but I don't think I understand what it is. I would be very grateful. Thanks, guys.

The ranks variable is a list of different numbers, is each number the number of relevant items retrieved from the model's predictor?
