### ISSUE TITLE
Testing Error::    start = offset_sessions[iters] IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by TauraiUCB** [hidasib/GRU4Rec#46]
Hi @hidasib 

I have trained the model on a different dataset using CPU. I followed the CPU configuration instructions and everything worked fine. Training was completed successfully but after loading the testing data, the model could not evaluate and I got this error:

```
data = pd.read_csv(fname, sep='\t', usecols=[gru.session_key, gru.item_key, gru.time_key], dtype={gru.session_key:'int32', gru.item_key:np.str})
Starting evaluation (cut-off=1, using standard mode for tiebreaking)
Measuring Recall@1 and MRR@1
Traceback (most recent call last):
  File "run.py", line 129, in <module>
    res = evaluation.evaluate_gpu(gru, test_data, items, batch_size=100, cut_off=c, mode=args.eval_type)
  File "/Users/xxxxxxxx/GRU4REC/GRU4Rec/evaluation.py", line 80, in evaluate_gpu
    start = offset_sessions[iters]
IndexError: index 2 is out of bounds for axis 0 with size 2
```
What could be causing this problem and how can I fix it?

Thanks

**Comment by LouHerGetUp** [comment]
> Hi @hidasib
> 
> I have trained the model on a different dataset using CPU. I followed the CPU configuration instructions and everything worked fine. Training was completed successfully but after loading the testing data, the model could not evaluate and I got this error:
> 
> ```
> data = pd.read_csv(fname, sep='\t', usecols=[gru.session_key, gru.item_key, gru.time_key], dtype={gru.session_key:'int32', gru.item_key:np.str})
> Starting evaluation (cut-off=1, using standard mode for tiebreaking)
> Measuring Recall@1 and MRR@1
> Traceback (most recent call last):
>   File "run.py", line 129, in <module>
>     res = evaluation.evaluate_gpu(gru, test_data, items, batch_size=100, cut_off=c, mode=args.eval_type)
>   File "/Users/xxxxxxxx/GRU4REC/GRU4Rec/evaluation.py", line 80, in evaluate_gpu
>     start = offset_sessions[iters]
> IndexError: index 2 is out of bounds for axis 0 with size 2
> ```
> 
> What could be causing this problem and how can I fix it?
> 
> Thanks

Hi, can you tell me how you solved this problem? I'm having the same problem.
